<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'getfly_id' => 12,
                'area' => 'Hà Nội',
                'code' => 'MJB00010',
                'name' => 'Tạ Văn Hợi',
                'title' => 'Team Leader (TL)',
                'email' => 'Takashi@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 13,
                'area' => 'Hà Nội',
                'code' => 'MJB00013',
                'name' => 'Nguyễn Hoành Đức',
                'title' => 'Team Leader (TL)',
                'email' => 'AlanNguyen@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 14,
                'area' => 'Hà Nội',
                'code' => 'MJB00026',
                'name' => 'Nguyễn Trà My',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'tramy9013@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 15,
                'area' => 'Hà Nội',
                'code' => 'MJB00030',
                'name' => 'Trần Văn Kiên',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'Tranvankien0210@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 16,
                'area' => 'Hà Nội',
                'code' => 'MJB00043',
                'name' => 'Phạm Thị Ngọc Ánh',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'anhpham30112002@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 17,
                'area' => 'Hà Nội',
                'code' => 'MJB00055',
                'name' => 'Lê Thị Hoài',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'HoaiLeta2001@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 18,
                'area' => 'Hà Nội',
                'code' => 'MJB00078',
                'name' => 'Nguyễn Văn Tạo',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'nguyenvantao262002@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 19,
                'area' => 'Hà Nội',
                'code' => 'MJB00085',
                'name' => 'Hoàng Thị Thu Trang',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'Thuhoang19092002@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 20,
                'area' => 'Hà Nội',
                'code' => 'MJB00091',
                'name' => 'Phan Thị Ngọc Nhung',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'Ngocnhung10112001@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 21,
                'area' => 'Hà Nội',
                'code' => 'MJB00111',
                'name' => 'Phạm Thị Thanh Huyền',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'Phamhuyen23092001@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 22,
                'area' => 'Hà Nội',
                'code' => 'MJB00127',
                'name' => 'Phạm Thị Hoài',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'Phamhoai14072001@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 23,
                'area' => 'Hà Nội',
                'code' => 'MJB00131',
                'name' => 'Phạm Thị Huyền Trang',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'Trangpham171001@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 24,
                'area' => 'Hà Nội',
                'code' => 'MJB00149',
                'name' => 'Lê Minh Anh',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'minhanhle911@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 25,
                'area' => 'Hà Nội',
                'code' => 'MJB00154',
                'name' => 'Phạm Thanh Trúc',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'trucpt2905@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 26,
                'area' => 'Hà Nội',
                'code' => 'MJB00174',
                'name' => 'Bùi Thu Trang',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'buithutrang2312@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 27,
                'area' => 'Hà Nội',
                'code' => 'MJB00196',
                'name' => 'Lương Xuân Bách',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'luongbach56@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 28,
                'area' => 'Hà Nội',
                'code' => 'MJB00200',
                'name' => 'Phạm Tú Anh',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'Ptuanh2910@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 29,
                'area' => 'Hà Nội',
                'code' => 'MJB00202',
                'name' => 'Lê Thị Vi Bằng',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'levibang1997@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 30,
                'area' => 'Hà Nội',
                'code' => 'MJB00203',
                'name' => 'Tạ Quốc Nam',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'namta7666@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 31,
                'area' => 'Hà Nội',
                'code' => 'MJB00204',
                'name' => 'Hà Trịnh Bữu Trim',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'habaomyxt@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 32,
                'area' => 'Hà Nội',
                'code' => 'MJB00100',
                'name' => 'Vũ Mạnh Quân',
                'title' => 'Giám đốc Marketing (CMO)',
                'email' => 'manhquanbk3@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'getfly_id' => 33,
                'area' => 'Hà Nội',
                'code' => 'MJB00031',
                'name' => 'Lương Minh Hải',
                'title' => 'Leader Makerting',
                'email' => 'Marketing@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
