<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00039',
                'name' => 'Phạm Nam Anh',
                'title' => 'Customer service Manager',
                'email' => 'phamnam2211@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('CRMmeijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00005',
                'name' => 'Nguyễn Mạnh Tráng',
                'title' => 'Điều Dưỡng Trưởng',
                'email' => 'Nurses@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('CRMmeijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00006',
                'name' => 'Trần Trà Mi',
                'title' => 'Điều Dưỡng',
                'email' => 'Nurses1@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00009',
                'name' => 'Trần Thị Thu Giang',
                'title' => 'Assistant Manager (AM)',
                'email' => 'Ginatran@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00010',
                'name' => 'Tạ Văn Hợi',
                'title' => 'Team Leader (TL)',
                'email' => 'Takashi@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00013',
                'name' => 'Nguyễn Hoành Đức',
                'title' => 'Team Leader (TL)',
                'email' => 'AlanNguyen@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00026',
                'name' => 'Nguyễn Trà My',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'tramy9013@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00016',
                'name' => 'Nguyễn Thị Thúy',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'tamdieuhanh1706@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00018',
                'name' => 'Nguyễn Hương Giang',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'zangnguyen49@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00019',
                'name' => 'Nguyễn Văn Nam',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'nguyenvannam1993hbl@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00069',
                'name' => 'Nguyễn Thị Nga',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'ngamc0408@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00023',
                'name' => 'Cao Thị Lan Anh',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'lananh2121997@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00149',
                'name' => 'Lê Minh Anh',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'minhanhle911@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00154',
                'name' => 'Phạm Thanh Trúc',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'trucpt2905@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00174',
                'name' => 'Bùi Thu Trang',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'buithutrang2312@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00196',
                'name' => 'Lương Xuân Bách',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'luongbach56@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00200',
                'name' => 'Phạm Tú Anh',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'Ptuanh2910@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00202',
                'name' => 'Lê Thị Vi Bằng',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'levibang1997@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00203',
                'name' => 'Tạ Quốc Nam',
                'title' => 'Chuyên viên tư vấn (HC)',
                'email' => 'namta7666@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00204',
                'name' => 'Hà Trịnh Bữu Trim',
                'title' => 'Chuyên viên tư vấn cấp cao (SHC)',
                'email' => 'habaomyxt@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00100',
                'name' => 'Vũ Mạnh Quân',
                'title' => 'Giám đốc Marketing (CMO)',
                'email' => 'manhquanbk3@gmail.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
            [
                'area' => 'Hà Nội',
                'code' => 'MJB00031',
                'name' => 'Lương Minh Hải',
                'title' => 'Leader Marketing',
                'email' => 'Marketing@meijibio.com',
                'phone' => null,
                'status' => 1,
                'password' => Hash::make('Meijibio2025@#!'),
            ],
        ];

        DB::table('users')->insert($users);
    }
}
